### ISSUE TITLE
OpenDoor() no longer works for sealed doors in 2.0+

### ISSUE THREAD

**Issue by Chudesnov** [Nats-ji/CyberpunkOpenSesameMod#1]
This no longer works for e.g. the church basement door in Pacifica.

https://github.com/Nats-ji/Cyberpunk-Open-Sesame-Mod/blob/9f019365356cbebbed38ee7b74e9d019fb26a65d/init.lua#L42

The solution can be found in AMM "Toggle Door Lock":

https://github.com/MaximiliumM/appearancemenumod/blob/795883ada11026d7da4c7305361973c8ee9a2d4f/Release/bin/x64/plugins/cyber_engine_tweaks/mods/AppearanceMenuMod/Modules/util.lua#L660-L668

**Comment by Nats-ji** [comment]
thanks
